kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        role: frontend
        env: dev
    spec:
      containers:
      - name: frontend
        image: "gcr.io/swn-jenkins/frontend:v1"
        imagePullPolicy: Always
        env: 
        - name: "NODE_ENV"
          value: "production"
        ports:
        - name: http
          containerPort: 8081
