branch-defaults:
  master:
    environment: swn-dev
    group_suffix: null
environment-defaults:
  SecondWindNation:
    branch: null
    repository: null
global:
  application_name: SecondWindNation
  branch: null
  default_ec2_keyname: secondWindNation
  default_platform: node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
