export default {
  objects: [
    {
      _id: '59c0c0ce54afe0d951000182',
      slug: 'sea-games-soh-rui-yong-defends-marathon-crown',
      title: 'SEA Games: Soh Rui Yong defends marathon crown',
      content: "<p><strong>Putrajaya, Malaysia,&nbsp;19 Aug 2017</strong> - For the second year running, Soh Rui Yong was not the favourite at the SEA Games marathon as he toed the line at 6 a.m. on Saturday.</p><p>But once again, Soh beat the odds. In the final turn of the 5-lap course surrounded by towering government buildings, the 2015 champion kicked down heavy favourite Agus Prayogo (Indonesia) to win in a time of 2 hours 29 minutes 27 seconds, a&nbsp;season best.</p><p>With 4 kilometres to go, Soh and Prayogo were the final two survivors of the initial lead pack of five, running side by side as the competitors in the community Larian Sukan SEA 2017 run cheered them on from the other side of the barrier.</p><p>At that moment, no one could predict the result. Prayogo owns faster PRs than Soh from the 5K to the marathon and owns more SEA Games medals. Soh was counting on his finishing speed to outkick his rivals if he could stick with them long enough.</p><p>The Singaporean had an extra&nbsp;motivator to perform well that morning &ndash; it was his father&#39;s 55th birthday, and a gold medal would be the perfect start to his day.</p><p>However, Prayogo was nowhere near the exuberant Soh, who was egging on a wildly cheering crowd and pointing&nbsp;at a stray cat. The Indonesian settled for silver with a time of 2:31:20.</p><p><span data-mce-style=\"font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;\">Initially, 2015 silver medalist Boonthung Srisung seemed to be in medal contention as he, Prayogo and Soh stuck with one another through the race.</span></p><p>However, Srisung cramped up with 10km remaining. After hobbling a few steps, he crumpled to the ground and&nbsp;was sent to the finish line in an ambulance. The Thai is penciled in for the 10,000-meter the following weekend.</p><p>That left the two Malaysians to battle for the bronze as they stuck to each other like glue, waiting for the opportunity to strike. Eventually, Muhaizar Mohamad emerged victorious, completing the race in 2:31:51 and 19 seconds ahead of countryman Leo Tan.</p><p>Fellow Singaporean Mok Ying Ren finished 7th of 15 competitors in 2:44:31.&nbsp;Unlike Soh, he did not have a pack to latch on to. Mok was left to reel in competitors one by one as he moved up the ranks from the back. Three men did not complete the course.</p><p>In the women&#39;s race, the Philippines&#39; Mary Joy Tabal dethroned 2015 champion&nbsp;Natthaya Thanaronnawat&nbsp;in a landslide victory of 2:48:26, more than 7 minutes clear of her next challenger. Singapore&#39;s Jasmine Goh, who spent most of the race tucked in 5th, caught one more challenger in the end stages of the race to place 4th (3:14:36).</p><p>Singapore&#39;s other runner, Rachel See, was the sixth finisher as she walked across the finish line in 3:46:41 while fending off stomach cramps.</p>",
      metafields: [
        {
          required: true,
          value: '45271d60-9d08-11e7-9b6e-cf699a098940-Soh Rui Yong_SEA Games 2017.jpg',
          key: 'header_image',
          title: 'Header Image',
          type: 'file',
          children: null,
          url: 'https://cosmicjs.com/uploads/45271d60-9d08-11e7-9b6e-cf699a098940-Soh Rui Yong_SEA Games 2017.jpg',
          imgix_url: 'https://cosmicjs.imgix.net/45271d60-9d08-11e7-9b6e-cf699a098940-Soh Rui Yong_SEA Games 2017.jpg',
        },
        {
          required: true,
          object_type: 'authors',
          value: '598d7b382f43f4ce200008af',
          key: 'author',
          title: 'Author',
          type: 'object',
          children: null,
          object: {
            _id: '598d7b382f43f4ce200008af',
            slug: 'romaine-soh',
            title: 'Romaine Soh',
            content: '',
            metafields: [
              {
                required: true,
                value: 'Romaine Soh',
                key: 'name',
                title: 'name',
                type: 'text',
                children: null,
              },
              {
                required: true,
                value: 'Romaine is an unapologetic athletics fan who believes that everyone has a good story waiting to be told. She tends to say hello to dogs first instead of their owners but is working on ironing out that bias.',
                key: 'short_description',
                title: 'short description',
                type: 'text',
                children: null,
              },
              {
                required: true,
                value: 'e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
                key: 'avatar',
                title: 'avatar',
                type: 'file',
                children: null,
                url: 'https://cosmicjs.com/uploads/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
                imgix_url: 'https://cosmicjs.imgix.net/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
              },
            ],
            bucket: '598281905ad4ceb3210002aa',
            type_slug: 'authors',
            created_at: '2017-08-11T09:39:04.581Z',
            created_by: '59804ab9b0086e1d6d000763',
            created: '2017-08-11T09:39:04.582Z',
            status: 'published',
            metadata: {
              name: 'Romaine Soh',
              short_description: 'Romaine is an unapologetic athletics fan who believes that everyone has a good story waiting to be told. She tends to say hello to dogs first instead of their owners but is working on ironing out that bias.',
              avatar: {
                url: 'https://cosmicjs.com/uploads/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
                imgix_url: 'https://cosmicjs.imgix.net/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
              },
            },
          },
        },
        {
          required: true,
          value: '2017-08-19',
          key: 'date',
          title: 'Date',
          type: 'date',
          children: null,
        },
        {
          required: true,
          options: [
            {
              key: 'Run',
              value: 'Running',
            },
            {
              key: 'Tri',
              value: 'Triathlon',
            },
            {
              key: 'General',
              value: 'General',
            },
            {
              key: 'Swim',
              value: 'Swimming',
            },
            {
              key: 'Bike',
              value: 'Cycling',
            },
          ],
          value: 'Running',
          key: 'category',
          title: 'Category',
          type: 'select-dropdown',
          children: null,
        },
        {
          required: true,
          object_type: 'posts',
          value: '59c0bee01a1faa9753000094,59c0bc781a1faa9753000058',
          key: 'related_articles',
          title: 'Related Articles',
          type: 'objects',
          children: null,
          objects: [
            {
              _id: '59c0bc781a1faa9753000058',
              slug: 'bryce-chong-ethel-lin-national-champions',
              title: 'Bryce Chong and Ethel Lin crowned national champions; final three Commonwealth Games nominations notched',
              content: '<p><strong>East Coast Park, SINGAPORE, 10 Sept 2017</strong> &ndash; The Singapore International Triathlon was a two-in-one meet for triathletes aiming to claim national glory.</p><p>Besides serving as a national championship, the Sunday morning race also served as the final qualifying meet for athletes aspiring to be nominated to next year&rsquo;s Commonwealth Games, with only two spots left for the women and one spot remaining for the men. The previous qualifying meet was the Osaka NTT ASTC Sprint Triathlon Asian Cup held last June, where SEA Games fourth-placer Christy Suriadi was the lone female representative. Nicholas Rachmadi and Bryce Chong also secured their nominations there.</p><p>While the concept of a national championships is not foreign, this year&rsquo;s championships had a slight twist. Not only did the elite triathletes have a designated local-only category, they were also allowed to draft, which allowed the competitors to adopt a pack strategy as they worked their way through the sprint-distance.</p><p>This resulted in Chong, Rachmadi, Aaron Kiss and Zacharias Low all exit the bike leg in a tight bunch. Chong managed to hold onto the lead as he crossed the line first in 1 hour, 1 minute 35 seconds, who was then followed by Low (1:02:08).</p><p>&ldquo;The goal was to just go hard today,&rdquo; said Chong, whose aim is to score sufficient ITU points to build a strong case for his nomination to compete at the Commonwealth Games.</p><p>It has been a turbulent year for Chong. Earlier&nbsp;this year, although the 19-year-old was pleased with his local performances, he failed to meet his own expectations at international meets and qualifiers, particularly the SEA Games trial.</p><p>Now, Chong has learned to enjoy himself at races instead of taking them too seriously, making small talk with his fellow athletes during and after the race. A coaching switch to Fabian William last July also proved beneficial as he was able to improve on his running, something Chong considers his weakest point.</p><p>For Low, this race was vital not only because it was a Commonwealth qualifier, but also because he has three weeks left before he enlists in national service. Although the Tri-Factor overall champion aims to maintain his fitness among his military responsibilities, his training will be limited to weekends when he books out, leaving his hands tied.</p><p>&ldquo;You can&rsquo;t save the world in two days,&rdquo; Low said with a laugh.</p><p>Chong and Low will compete once again at the Murakami NTT ASTC Triathlon Asian Cup in two weeks, where they will face off over the standard course.</p><dl data-mce-style="width: 1034px;" id="attachment_4947"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/09/DSC_5279_web-1024x682.jpg" alt="" width="1024" height="682" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/09/DSC_5279_web-1024x682.jpg" class="fr-fic fr-dii hoverZoomLink"></dt><dd>The women&#39;s elite category podium finishers. L to R: Phoebe Kee (2nd), Ethel Lin (1st), Chang Shuwen (3rd).</dd></dl><p>While there were only three female elite competitors, champion Lin (1:12:37) was undeterred by the small field, even facing strong competition from runner-up Phoebe Kee (1:13:29). At the start line, Lin, 30, asked Kee, 17, for her age.</p><p>Perhaps counter-intuitively, the sizable age gap motivated Lin, who is just two months back into training after recovering from injury. The decision to race was a last-minute one, and it paid off handsomely as she secured a Commonwealth nomination.</p><p>&ldquo;I never expected to be here two months ago,&rdquo; said Lin, who credited Trackstar Athletics coach Elangovan Ganesan. &ldquo;(I&rsquo;m just proud) that I turned up today, really, even though I&rsquo;m at 80 percent.&rdquo;</p><p>Kee and Lin capitalized on the draft-legal rule to work together on the first lap of the bike. Lin, however, harbored an unconscious fear of Kee&rsquo;s capability to run an 11-minute 3K and gapped her within the first lap to create a buffer on the running leg.</p><p>Lin&rsquo;s current training focuses more on endurance, geared toward her immediate goal of completing a 70.3 Ironman Triathlon at the end of the year. Though she has yet to decide her race schedule for the rest of the year, Lin plans to revisit international&nbsp;meets &ndash; after she returns to 100 percent.</p><p>&quot;For now, it&#39;s nice to race your first (without the international competition),&quot; she said with a laugh.</p><p><em>Full National Championships results <a data-mce-href="https://www.sportstats.asia/display-results.xhtml?raceid=46923" href="https://www.sportstats.asia/display-results.xhtml?raceid=46923">here</a>. Find the rest of the results on the event <a data-mce-href="http://www.triathlon.sg/results/" href="http://www.triathlon.sg/results/">website</a>.</em></p>',
              metafields: [
                {
                  required: true,
                  value: '9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                  key: 'header_image',
                  title: 'Header Image',
                  type: 'file',
                  children: null,
                  url: 'https://cosmicjs.com/uploads/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                  imgix_url: 'https://cosmicjs.imgix.net/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                },
                {
                  required: true,
                  object_type: 'authors',
                  value: '598d7b382f43f4ce200008af',
                  key: 'author',
                  title: 'Author',
                  type: 'object',
                  children: null,
                },
                {
                  required: true,
                  value: '2017-09-10',
                  key: 'date',
                  title: 'Date',
                  type: 'date',
                  children: null,
                },
                {
                  required: true,
                  options: [
                    {
                      key: 'Run',
                      value: 'Running',
                    },
                    {
                      key: 'Tri',
                      value: 'Triathlon',
                    },
                    {
                      key: 'General',
                      value: 'General',
                    },
                    {
                      key: 'Swim',
                      value: 'Swimming',
                    },
                    {
                      key: 'Bike',
                      value: 'Cycling',
                    },
                  ],
                  value: 'Triathlon',
                  key: 'category',
                  title: 'Category',
                  type: 'select-dropdown',
                  children: null,
                },
              ],
              bucket: '598281905ad4ceb3210002aa',
              type_slug: 'posts',
              created_at: '2017-09-19T06:43:04.770Z',
              created_by: '59aa3a0886be747f35000b2e',
              created: '2017-09-19T06:43:04.770Z',
              status: 'published',
              modified_at: '2017-09-19T06:43:22.607Z',
              modified_by: '59aa3a0886be747f35000b2e',
              publish_at: null,
              metadata: {
                header_image: {
                  url: 'https://cosmicjs.com/uploads/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                  imgix_url: 'https://cosmicjs.imgix.net/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                },
                date: '2017-09-10',
                category: 'Triathlon',
              },
            },
            {
              _id: '59c0bee01a1faa9753000094',
              slug: 'sea-games-philippines-claim-top-four-triathlon-medals',
              title: 'SEA Games: Philippines claim top four triathlon medals; Singapore and Malaysia win bronze',
              content: '<p><strong>Putrajaya, Malaysia, 21 August 2017 &ndash;</strong> The Philippines continued their dominant streak in the triathlon as they swept both the men&#39;s and women&#39;s titles once again at the SEA Games triathlon on Monday morning at the Water Sport Complex in Presint 6.</p><p>Nikko Huelgas, the 2015 champion, defended his title as he completed the 1.5-kilometre swim, 40 km bike and 10 km run course in 1 hour 59 minutes 30 seconds. Fellow Filipino John Chicano was the next man to cross the line as he stopped the clock at 2:01:27,&nbsp;bringing the&nbsp;Philippines to a 1-2 finish.</p><p>The Philippine women also earned a 1-2 finish as Kim Mangrobang (2:11:14) sped away from 2015 champion Claire Adorna (2:18:58) during the run leg to become the 2017 champion.</p><p>There was a shift in the men&#39;s ranks as Singaporean Clement Chow, who took two months of no-pay leave to train for the Games, snuck onto the podium to claim his first SEA Games medal ahead of fellow countryman and 2015 bronze medalist Wille Loo. While Chow and Loo were still together at the first transition,&nbsp;the former stayed on Huelgas to pull ahead during the first lap of the bike leg. Chow exited the second transition in second place.</p><p>However, Chicano caught a tiring Chow&nbsp;midway through the 10 km&nbsp;course and continued to increase his lead. Chow was left to tough it out alone as he struggled to keep his medal hopes alive. He eventually clinched the bronze in 2:03:24, ahead of Loo&#39;s 2:04:33.</p><dl data-mce-style="width: 1260px;" id="attachment_4902"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4217.jpg" alt="" width="1250" height="833" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4217.jpg" class="fr-fic fr-dii"></dt><dd>Clement Chow (right) sticks close to back-to-back triathlon champion Nikko Huelgas. Chow exited the bike leg 2nd during the 2017 SEA Games and eventually won a bronze medal.</dd></dl><p>In the women&#39;s race, Singaporeans Christy Suriadi and Denise Chia stuck together through the swim and bike elements as they fed off each other&#39;s energy to narrow the gap on the rest of the field. They weren&#39;t the only ones with the same idea &ndash; Filipinas Mangrobang and Adorna, and Malaysians Irene Chong and Zoe Bowden came through the first transition side by side as well.</p><p>Over the course of the cycling leg, Chong and Bowden increased their 3-minute advantage to 6, but both appeared to&nbsp;be extremely fatigued by the time they entered the last element as Suriadi mowed down a slowing Bowden to move up to fourth.</p><dl data-mce-style="width: 1260px;" id="attachment_4906"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4372.jpg" alt="" width="1250" height="833" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4372.jpg" class="fr-fic fr-dii"></dt><dd>Malaysians Irene Chong and Zoe Bowden stick together in the bike portion at the 2017 SEA Games.</dd></dl><p>At the final lap, Suriadi seemed to be within striking distance of a medal, with only 3 minutes separating her from third place Chong. Though the Malaysian was visibly fatigued throughout the running portion, Chong had the home crowd support.&nbsp;Additionally,&nbsp;seeing a bouncy Suriadi as she rounded the final U-turn was enough motivation for Chong to drive her legs and maintain the gap to ensure a medal for the host.</p><p>While the medalists are seasoned triathletes, junior athletes Suriadi, Bowden and Chia are new faces in the SEA Games field. None of them are older than 20.</p><p>&quot;I was nervous but also really excited for my debut SEA games,&quot; said Suriadi, 20. &quot;Denise and I had to constantly remind ourselves that we were actually competing in the SEA games because it was so surreal.&quot;</p><p>Despite a &quot;tough start&quot; &ndash; Suriadi fell behind the chase pack and lost her swim cap right at the start &ndash; she was excited about placing fourth at one of the biggest regional competitions.</p><p>&quot;It was such an amazing experience to be a part of the high-energy atmosphere and racing with the best of Southeast Asia,&quot; she said.</p><dl data-mce-style="width: 1260px;" id="attachment_4907"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4518.jpg" alt="" width="1250" height="833" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4518.jpg" class="fr-fic fr-dii"></dt><dd>Singaporeans Christy Suriadi (right) and Denise Chia (left) run together during the first lap at the 2017 SEA Games.</dd></dl><p><em>View the <a data-mce-href="http://www.triathlon.org/events/event/2017_kuala_lumpur_south_east_asian_games" href="http://www.triathlon.org/events/event/2017_kuala_lumpur_south_east_asian_games">full results</a>.</em></p>',
              metafields: [
                {
                  required: true,
                  value: 'b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                  key: 'header_image',
                  title: 'Header Image',
                  type: 'file',
                  children: null,
                  url: 'https://cosmicjs.com/uploads/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                  imgix_url: 'https://cosmicjs.imgix.net/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                },
                {
                  required: true,
                  object_type: 'authors',
                  value: '598d7b382f43f4ce200008af',
                  key: 'author',
                  title: 'Author',
                  type: 'object',
                  children: null,
                },
                {
                  required: true,
                  value: '2017-08-21',
                  key: 'date',
                  title: 'Date',
                  type: 'date',
                  children: null,
                },
                {
                  required: true,
                  options: [
                    {
                      key: 'Run',
                      value: 'Running',
                    },
                    {
                      key: 'Tri',
                      value: 'Triathlon',
                    },
                    {
                      key: 'General',
                      value: 'General',
                    },
                    {
                      key: 'Swim',
                      value: 'Swimming',
                    },
                    {
                      key: 'Bike',
                      value: 'Cycling',
                    },
                  ],
                  value: 'Triathlon',
                  key: 'category',
                  title: 'Category',
                  type: 'select-dropdown',
                  children: null,
                },
              ],
              bucket: '598281905ad4ceb3210002aa',
              type_slug: 'posts',
              created_at: '2017-09-19T06:53:19.806Z',
              created_by: '59aa3a0886be747f35000b2e',
              created: '2017-09-19T06:53:19.806Z',
              status: 'published',
              modified_at: '2017-09-19T07:00:14.482Z',
              modified_by: '59aa3a0886be747f35000b2e',
              publish_at: null,
              metadata: {
                header_image: {
                  url: 'https://cosmicjs.com/uploads/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                  imgix_url: 'https://cosmicjs.imgix.net/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                },
                date: '2017-08-21',
                category: 'Triathlon',
              },
            },
          ],
        },
      ],
      bucket: '598281905ad4ceb3210002aa',
      type_slug: 'posts',
      created_at: '2017-09-19T07:01:33.935Z',
      created_by: '59aa3a0886be747f35000b2e',
      created: '2017-09-19T07:01:33.935Z',
      status: 'published',
      modified_at: '2017-09-19T07:40:48.748Z',
      modified_by: '59804ab9b0086e1d6d000763',
      publish_at: null,
      metadata: {
        header_image: {
          url: 'https://cosmicjs.com/uploads/45271d60-9d08-11e7-9b6e-cf699a098940-Soh Rui Yong_SEA Games 2017.jpg',
          imgix_url: 'https://cosmicjs.imgix.net/45271d60-9d08-11e7-9b6e-cf699a098940-Soh Rui Yong_SEA Games 2017.jpg',
        },
        author: {
          _id: '598d7b382f43f4ce200008af',
          slug: 'romaine-soh',
          title: 'Romaine Soh',
          content: '',
          metafields: [
            {
              required: true,
              value: 'Romaine Soh',
              key: 'name',
              title: 'name',
              type: 'text',
              children: null,
            },
            {
              required: true,
              value: 'Romaine is an unapologetic athletics fan who believes that everyone has a good story waiting to be told. She tends to say hello to dogs first instead of their owners but is working on ironing out that bias.',
              key: 'short_description',
              title: 'short description',
              type: 'text',
              children: null,
            },
            {
              required: true,
              value: 'e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
              key: 'avatar',
              title: 'avatar',
              type: 'file',
              children: null,
              url: 'https://cosmicjs.com/uploads/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
              imgix_url: 'https://cosmicjs.imgix.net/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
            },
          ],
          bucket: '598281905ad4ceb3210002aa',
          type_slug: 'authors',
          created_at: '2017-08-11T09:39:04.581Z',
          created_by: '59804ab9b0086e1d6d000763',
          created: '2017-08-11T09:39:04.582Z',
          status: 'published',
          metadata: {
            name: 'Romaine Soh',
            short_description: 'Romaine is an unapologetic athletics fan who believes that everyone has a good story waiting to be told. She tends to say hello to dogs first instead of their owners but is working on ironing out that bias.',
            avatar: {
              url: 'https://cosmicjs.com/uploads/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
              imgix_url: 'https://cosmicjs.imgix.net/e6f52410-7e78-11e7-afea-b7512553e71a-romaine_soh.jpg',
            },
          },
        },
        date: '2017-08-19',
        category: 'Running',
        related_articles: [
          {
            _id: '59c0bc781a1faa9753000058',
            slug: 'bryce-chong-ethel-lin-national-champions',
            title: 'Bryce Chong and Ethel Lin crowned national champions; final three Commonwealth Games nominations notched',
            content: '<p><strong>East Coast Park, SINGAPORE, 10 Sept 2017</strong> &ndash; The Singapore International Triathlon was a two-in-one meet for triathletes aiming to claim national glory.</p><p>Besides serving as a national championship, the Sunday morning race also served as the final qualifying meet for athletes aspiring to be nominated to next year&rsquo;s Commonwealth Games, with only two spots left for the women and one spot remaining for the men. The previous qualifying meet was the Osaka NTT ASTC Sprint Triathlon Asian Cup held last June, where SEA Games fourth-placer Christy Suriadi was the lone female representative. Nicholas Rachmadi and Bryce Chong also secured their nominations there.</p><p>While the concept of a national championships is not foreign, this year&rsquo;s championships had a slight twist. Not only did the elite triathletes have a designated local-only category, they were also allowed to draft, which allowed the competitors to adopt a pack strategy as they worked their way through the sprint-distance.</p><p>This resulted in Chong, Rachmadi, Aaron Kiss and Zacharias Low all exit the bike leg in a tight bunch. Chong managed to hold onto the lead as he crossed the line first in 1 hour, 1 minute 35 seconds, who was then followed by Low (1:02:08).</p><p>&ldquo;The goal was to just go hard today,&rdquo; said Chong, whose aim is to score sufficient ITU points to build a strong case for his nomination to compete at the Commonwealth Games.</p><p>It has been a turbulent year for Chong. Earlier&nbsp;this year, although the 19-year-old was pleased with his local performances, he failed to meet his own expectations at international meets and qualifiers, particularly the SEA Games trial.</p><p>Now, Chong has learned to enjoy himself at races instead of taking them too seriously, making small talk with his fellow athletes during and after the race. A coaching switch to Fabian William last July also proved beneficial as he was able to improve on his running, something Chong considers his weakest point.</p><p>For Low, this race was vital not only because it was a Commonwealth qualifier, but also because he has three weeks left before he enlists in national service. Although the Tri-Factor overall champion aims to maintain his fitness among his military responsibilities, his training will be limited to weekends when he books out, leaving his hands tied.</p><p>&ldquo;You can&rsquo;t save the world in two days,&rdquo; Low said with a laugh.</p><p>Chong and Low will compete once again at the Murakami NTT ASTC Triathlon Asian Cup in two weeks, where they will face off over the standard course.</p><dl data-mce-style="width: 1034px;" id="attachment_4947"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/09/DSC_5279_web-1024x682.jpg" alt="" width="1024" height="682" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/09/DSC_5279_web-1024x682.jpg" class="fr-fic fr-dii hoverZoomLink"></dt><dd>The women&#39;s elite category podium finishers. L to R: Phoebe Kee (2nd), Ethel Lin (1st), Chang Shuwen (3rd).</dd></dl><p>While there were only three female elite competitors, champion Lin (1:12:37) was undeterred by the small field, even facing strong competition from runner-up Phoebe Kee (1:13:29). At the start line, Lin, 30, asked Kee, 17, for her age.</p><p>Perhaps counter-intuitively, the sizable age gap motivated Lin, who is just two months back into training after recovering from injury. The decision to race was a last-minute one, and it paid off handsomely as she secured a Commonwealth nomination.</p><p>&ldquo;I never expected to be here two months ago,&rdquo; said Lin, who credited Trackstar Athletics coach Elangovan Ganesan. &ldquo;(I&rsquo;m just proud) that I turned up today, really, even though I&rsquo;m at 80 percent.&rdquo;</p><p>Kee and Lin capitalized on the draft-legal rule to work together on the first lap of the bike. Lin, however, harbored an unconscious fear of Kee&rsquo;s capability to run an 11-minute 3K and gapped her within the first lap to create a buffer on the running leg.</p><p>Lin&rsquo;s current training focuses more on endurance, geared toward her immediate goal of completing a 70.3 Ironman Triathlon at the end of the year. Though she has yet to decide her race schedule for the rest of the year, Lin plans to revisit international&nbsp;meets &ndash; after she returns to 100 percent.</p><p>&quot;For now, it&#39;s nice to race your first (without the international competition),&quot; she said with a laugh.</p><p><em>Full National Championships results <a data-mce-href="https://www.sportstats.asia/display-results.xhtml?raceid=46923" href="https://www.sportstats.asia/display-results.xhtml?raceid=46923">here</a>. Find the rest of the results on the event <a data-mce-href="http://www.triathlon.sg/results/" href="http://www.triathlon.sg/results/">website</a>.</em></p>',
            metafields: [
              {
                required: true,
                value: '9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                key: 'header_image',
                title: 'Header Image',
                type: 'file',
                children: null,
                url: 'https://cosmicjs.com/uploads/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                imgix_url: 'https://cosmicjs.imgix.net/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
              },
              {
                required: true,
                object_type: 'authors',
                value: '598d7b382f43f4ce200008af',
                key: 'author',
                title: 'Author',
                type: 'object',
                children: null,
              },
              {
                required: true,
                value: '2017-09-10',
                key: 'date',
                title: 'Date',
                type: 'date',
                children: null,
              },
              {
                required: true,
                options: [
                  {
                    key: 'Run',
                    value: 'Running',
                  },
                  {
                    key: 'Tri',
                    value: 'Triathlon',
                  },
                  {
                    key: 'General',
                    value: 'General',
                  },
                  {
                    key: 'Swim',
                    value: 'Swimming',
                  },
                  {
                    key: 'Bike',
                    value: 'Cycling',
                  },
                ],
                value: 'Triathlon',
                key: 'category',
                title: 'Category',
                type: 'select-dropdown',
                children: null,
              },
            ],
            bucket: '598281905ad4ceb3210002aa',
            type_slug: 'posts',
            created_at: '2017-09-19T06:43:04.770Z',
            created_by: '59aa3a0886be747f35000b2e',
            created: '2017-09-19T06:43:04.770Z',
            status: 'published',
            modified_at: '2017-09-19T06:43:22.607Z',
            modified_by: '59aa3a0886be747f35000b2e',
            publish_at: null,
            metadata: {
              header_image: {
                url: 'https://cosmicjs.com/uploads/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
                imgix_url: 'https://cosmicjs.imgix.net/9f14fe80-9d05-11e7-8cb5-e5753be725a9-bryce.jpg',
              },
              date: '2017-09-10',
              category: 'Triathlon',
            },
          },
          {
            _id: '59c0bee01a1faa9753000094',
            slug: 'sea-games-philippines-claim-top-four-triathlon-medals',
            title: 'SEA Games: Philippines claim top four triathlon medals; Singapore and Malaysia win bronze',
            content: '<p><strong>Putrajaya, Malaysia, 21 August 2017 &ndash;</strong> The Philippines continued their dominant streak in the triathlon as they swept both the men&#39;s and women&#39;s titles once again at the SEA Games triathlon on Monday morning at the Water Sport Complex in Presint 6.</p><p>Nikko Huelgas, the 2015 champion, defended his title as he completed the 1.5-kilometre swim, 40 km bike and 10 km run course in 1 hour 59 minutes 30 seconds. Fellow Filipino John Chicano was the next man to cross the line as he stopped the clock at 2:01:27,&nbsp;bringing the&nbsp;Philippines to a 1-2 finish.</p><p>The Philippine women also earned a 1-2 finish as Kim Mangrobang (2:11:14) sped away from 2015 champion Claire Adorna (2:18:58) during the run leg to become the 2017 champion.</p><p>There was a shift in the men&#39;s ranks as Singaporean Clement Chow, who took two months of no-pay leave to train for the Games, snuck onto the podium to claim his first SEA Games medal ahead of fellow countryman and 2015 bronze medalist Wille Loo. While Chow and Loo were still together at the first transition,&nbsp;the former stayed on Huelgas to pull ahead during the first lap of the bike leg. Chow exited the second transition in second place.</p><p>However, Chicano caught a tiring Chow&nbsp;midway through the 10 km&nbsp;course and continued to increase his lead. Chow was left to tough it out alone as he struggled to keep his medal hopes alive. He eventually clinched the bronze in 2:03:24, ahead of Loo&#39;s 2:04:33.</p><dl data-mce-style="width: 1260px;" id="attachment_4902"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4217.jpg" alt="" width="1250" height="833" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4217.jpg" class="fr-fic fr-dii"></dt><dd>Clement Chow (right) sticks close to back-to-back triathlon champion Nikko Huelgas. Chow exited the bike leg 2nd during the 2017 SEA Games and eventually won a bronze medal.</dd></dl><p>In the women&#39;s race, Singaporeans Christy Suriadi and Denise Chia stuck together through the swim and bike elements as they fed off each other&#39;s energy to narrow the gap on the rest of the field. They weren&#39;t the only ones with the same idea &ndash; Filipinas Mangrobang and Adorna, and Malaysians Irene Chong and Zoe Bowden came through the first transition side by side as well.</p><p>Over the course of the cycling leg, Chong and Bowden increased their 3-minute advantage to 6, but both appeared to&nbsp;be extremely fatigued by the time they entered the last element as Suriadi mowed down a slowing Bowden to move up to fourth.</p><dl data-mce-style="width: 1260px;" id="attachment_4906"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4372.jpg" alt="" width="1250" height="833" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4372.jpg" class="fr-fic fr-dii"></dt><dd>Malaysians Irene Chong and Zoe Bowden stick together in the bike portion at the 2017 SEA Games.</dd></dl><p>At the final lap, Suriadi seemed to be within striking distance of a medal, with only 3 minutes separating her from third place Chong. Though the Malaysian was visibly fatigued throughout the running portion, Chong had the home crowd support.&nbsp;Additionally,&nbsp;seeing a bouncy Suriadi as she rounded the final U-turn was enough motivation for Chong to drive her legs and maintain the gap to ensure a medal for the host.</p><p>While the medalists are seasoned triathletes, junior athletes Suriadi, Bowden and Chia are new faces in the SEA Games field. None of them are older than 20.</p><p>&quot;I was nervous but also really excited for my debut SEA games,&quot; said Suriadi, 20. &quot;Denise and I had to constantly remind ourselves that we were actually competing in the SEA games because it was so surreal.&quot;</p><p>Despite a &quot;tough start&quot; &ndash; Suriadi fell behind the chase pack and lost her swim cap right at the start &ndash; she was excited about placing fourth at one of the biggest regional competitions.</p><p>&quot;It was such an amazing experience to be a part of the high-energy atmosphere and racing with the best of Southeast Asia,&quot; she said.</p><dl data-mce-style="width: 1260px;" id="attachment_4907"><dt><img src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4518.jpg" alt="" width="1250" height="833" data-mce-src="http://secondwindmagazine.com/wp-content/uploads/2017/08/DSC_4518.jpg" class="fr-fic fr-dii"></dt><dd>Singaporeans Christy Suriadi (right) and Denise Chia (left) run together during the first lap at the 2017 SEA Games.</dd></dl><p><em>View the <a data-mce-href="http://www.triathlon.org/events/event/2017_kuala_lumpur_south_east_asian_games" href="http://www.triathlon.org/events/event/2017_kuala_lumpur_south_east_asian_games">full results</a>.</em></p>',
            metafields: [
              {
                required: true,
                value: 'b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                key: 'header_image',
                title: 'Header Image',
                type: 'file',
                children: null,
                url: 'https://cosmicjs.com/uploads/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                imgix_url: 'https://cosmicjs.imgix.net/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
              },
              {
                required: true,
                object_type: 'authors',
                value: '598d7b382f43f4ce200008af',
                key: 'author',
                title: 'Author',
                type: 'object',
                children: null,
              },
              {
                required: true,
                value: '2017-08-21',
                key: 'date',
                title: 'Date',
                type: 'date',
                children: null,
              },
              {
                required: true,
                options: [
                  {
                    key: 'Run',
                    value: 'Running',
                  },
                  {
                    key: 'Tri',
                    value: 'Triathlon',
                  },
                  {
                    key: 'General',
                    value: 'General',
                  },
                  {
                    key: 'Swim',
                    value: 'Swimming',
                  },
                  {
                    key: 'Bike',
                    value: 'Cycling',
                  },
                ],
                value: 'Triathlon',
                key: 'category',
                title: 'Category',
                type: 'select-dropdown',
                children: null,
              },
            ],
            bucket: '598281905ad4ceb3210002aa',
            type_slug: 'posts',
            created_at: '2017-09-19T06:53:19.806Z',
            created_by: '59aa3a0886be747f35000b2e',
            created: '2017-09-19T06:53:19.806Z',
            status: 'published',
            modified_at: '2017-09-19T07:00:14.482Z',
            modified_by: '59aa3a0886be747f35000b2e',
            publish_at: null,
            metadata: {
              header_image: {
                url: 'https://cosmicjs.com/uploads/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
                imgix_url: 'https://cosmicjs.imgix.net/b93b3800-9d06-11e7-a65f-0708bbef090c-Nikko Huelgas_2017 SEA Games Triathlon.jpg',
              },
              date: '2017-08-21',
              category: 'Triathlon',
            },
          },
        ],
      },
    },
  ],
};
