kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend-canary
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: "gcr.io/swn-jenkins/frontend:v1"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
