kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend-production
spec:
  replicas:
  template:
    metadata:
      name: swn-frontend
      labels:
        app: frontend
        role: frontend
        env: production 
    spec:
      containers:
      - name: frontend
        image: "gcr.io/swn-jenkins/swn:dev-jenkins.20" 
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 8081
