kind: Service
apiVersion: v1
metadata:
  name: "swn-frontend"
spec:
  type: LoadBalancer
  loadBalancerIP: "35.186.157.186"
  selector:
    app: "frontend"
    role: frontend
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 8081
